version: '3.8'

services:
  frontend2:
    build:
      context: ./frontend2
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend2:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=https://habkah.alrumahi.site
      - VITE_NODE_ENV=production
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8001"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/story_twister
      - GROQ_API_KEY=${GROQ_API_KEY:-}
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=story_twister
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

volumes:
  postgres_data_prod:
