version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8001

  frontend2:
    build:
      context: ./frontend2
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend2:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8001

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/story_twister
      - GROQ_API_KEY=${GROQ_API_KEY:-}
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=story_twister
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
