"""Add ended_at to sessions

Revision ID: 573e8f76f1a6
Revises: cea1e6a1fb32
Create Date: 2025-08-09 06:23:04.240731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573e8f76f1a6'
down_revision = 'cea1e6a1fb32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('ended_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'ended_at')
    # ### end Alembic commands ###
