"""Add session analysis model

Revision ID: c2dd74d42738
Revises: 422ec4104403
Create Date: 2025-08-08 08:06:07.670186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2dd74d42738'
down_revision = '422ec4104403'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('creativity_score', sa.Integer(), nullable=False),
    sa.Column('engagement_score', sa.Integer(), nullable=False),
    sa.Column('collaboration_score', sa.Integer(), nullable=False),
    sa.Column('creativity_feedback', sa.Text(), nullable=False),
    sa.Column('engagement_feedback', sa.Text(), nullable=False),
    sa.Column('collaboration_feedback', sa.Text(), nullable=False),
    sa.Column('total_turns', sa.Integer(), nullable=False),
    sa.Column('unique_participants', sa.Integer(), nullable=False),
    sa.Column('session_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_analyses')
    # ### end Alembic commands ###
